### ISSUE TITLE
issue with string literal

### ISSUE THREAD

**Issue by doongjohn** [aMOPel/nvim-treesitter-nim#2]
string literal query is not working after this update: https://github.com/alaviss/tree-sitter-nim/commit/98272878bf1b7d7ce0b1d146a021888eb6d66834

**Comment by aMOPel** [comment]
Did you update the parser manually somehow? I thought the rev is pinned and you will always get the same (currently supported) parser version when using `:TSInstall`/`:TSUpdate`

I am currently working on  another [PR](https://github.com/nvim-treesitter/nvim-treesitter/pull/5556#) to nvim-treesitter, which contains many updates including support for the latest parser version

**Comment by doongjohn** [comment]
Yes, I am using the manually git cloned parser path. (I did't know pinned rev was a thing 😮)

**Comment by aMOPel** [comment]
nvim-treesitter has a lockfile.json. Every parser is pinned, exactly because of those breaking changes.
